# Generated by Django 3.0.6 on 2020-05-10 05:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PicturesCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pictures_category', models.CharField(max_length=200)),
                ('category_summary', models.CharField(max_length=200)),
                ('category_slug', models.CharField(default=1, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PicturesSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pictures_series', models.CharField(max_length=200)),
                ('series_summary', models.CharField(max_length=200)),
                ('pictures_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='sub1.PicturesCategory', verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='pictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pictures_title', models.CharField(max_length=200)),
                ('pictures_content', models.TextField()),
                ('pictures_published', models.DateTimeField(default=datetime.datetime(2020, 5, 10, 11, 0, 2, 361795), verbose_name='date published')),
                ('pictures_slug', models.CharField(default=1, max_length=200)),
                ('pictures_series', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='sub1.PicturesSeries', verbose_name='Series')),
            ],
        ),
    ]
