# Generated by Django 3.0.6 on 2020-05-10 05:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='pictures_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 10, 11, 0, 48, 874790), verbose_name='date published'),
        ),
    ]
